[build-system]
requires = ["setuptools>=40.6.0"]
build-backend = "setuptools.build_meta"

[project]
# Replace with your project name
name = "Price Prediction"

# Replace with your version number
version = "0.1.0"

# List your dependencies here
dependencies = [
    "altair==5.0.1",
    "astroid==2.3.3",
    "attrs==23.2.0",
    "backports.zoneinfo==0.2.1",
    "blinker==1.6.3",
    "cachetools==5.3.3",
    "certifi==2024.6.2",
    "charset-normalizer==3.3.2",
    "Click==7.0",
    "decorator==5.1.1",
    "docopt==0.6.2",
    "Flask==1.0.2",
    "gitdb==4.0.11",
    "GitPython==3.1.43",
    "idna==3.7",
    "importlib-metadata==6.7.0",
    "importlib-resources==5.12.0",
    "isort==4.3.21",
    "itsdangerous==1.1.0",
    "Jinja2==2.10.3",
    "jsonschema==4.17.3",
    "lazy-object-proxy==1.4.3",
    "markdown-it-py==2.2.0",
    "MarkupSafe==1.1.1",
    "mccabe==0.6.1",
    "mdurl==0.1.2",
    "numpy==1.21.6",
    "packaging==23.2",
    "pandas==1.3.5",
    "Pillow==9.5.0",
    "pipreqs==0.4.13",
    "pkgutil_resolve_name==1.3.10",
    "protobuf==4.24.4",
    "pyarrow==12.0.1",
    "pydeck==0.8.1b1",
    "Pygments==2.17.2",
    "pylint==2.4.4",
    "Pympler==1.0.1",
    "pyrsistent==0.19.3",
    "python-dateutil==2.8.0",
    "pytz==2019.3",
    "pytz-deprecation-shim==0.1.0.post0",
    "requests==2.31.0",
    "rich==13.7.1",
    "scikit-learn==0.20.3",
    "scipy==1.3.1",
    "six==1.12.0",
    "smmap==5.0.1",
    "streamlit==1.23.1",
    "tenacity==8.2.3",
    "toml==0.10.2",
    "toolz==0.12.1",
    "tornado==6.2",
    "typed-ast==1.4.3",
    "typing_extensions==4.7.1",
    "tzdata==2024.1",
    "tzlocal==4.3.1",
    "urllib3==2.0.7",
    "validators==0.20.0",
    "watchdog==3.0.0",
    "Werkzeug==0.16.0",
    "wrapt==1.11.2",
    "yarg==0.1.9",
    "zipp==3.15.0",
]
